function Reset_fits(hObject, eventdata, handles)

set(handles.D_fit,'String','Not fitted')
set(handles.E_fit,'String','Not fitted')
set(handles.gx_fit,'String','Not fitted')
set(handles.gy_fit,'String','Not fitted')
set(handles.gz_fit,'String','Not fitted')
set(handles.S_fit,'String','Not fitted')
set(handles.J0_fit,'String','Not fitted')

set(handles.D_min,'String','-')
set(handles.E_min,'String','-')
set(handles.gx_min,'String','-')
set(handles.gy_min,'String','-')
set(handles.gz_min,'String','-')
set(handles.S_min,'String','-')
set(handles.J0_min,'String','-')

set(handles.D_max,'String','-')
set(handles.E_max,'String','-')
set(handles.gx_max,'String','-')
set(handles.gy_max,'String','-')
set(handles.gz_max,'String','-')
set(handles.S_max,'String','-')
set(handles.J0_max,'String','-')